import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/views/**/*.html',
        './resources/js/**/*.js',
        './resources/js/**/*.vue',
    ],

    darkMode: 'class',

    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                display: ['Inter', ...defaultTheme.fontFamily.sans],
            },

            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },

                navy: {
                    DEFAULT: '#161758',
                    deep: '#090C2E',
                    light: '#27438D',
                },
                cyan: {
                    DEFAULT: '#00A2E9',
                },
                brand: {
                    50: '#eef3ff',
                    100: '#d9e4ff',
                    200: '#bcd0ff',
                    300: '#8eb3ff',
                    400: '#598bff',
                    500: '#3366ff',
                    600: '#1a44f5',
                    700: '#1333e1',
                    800: '#162cb6',
                    900: '#161758',
                    950: '#0d0e36',
                },
                gold: {
                    400: '#FCC626',
                    500: '#f5b800',
                    600: '#d4a00a',
                },
                success: {
                    50: '#f0fdf4',
                    500: '#22c55e',
                    600: '#16a34a',
                },
                danger: {
                    50: '#fef2f2',
                    500: '#ef4444',
                    600: '#dc2626',
                },
            },

            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
                '2xl': '1rem',
                '3xl': '1.25rem',
                '4xl': '1.5rem',
            },

            boxShadow: {
                'card': '0 1px 3px 0 rgb(0 0 0 / 0.04), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
                'card-hover': '0 10px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.04)',
                'card-lg': '0 20px 40px -8px rgb(0 0 0 / 0.1), 0 8px 16px -6px rgb(0 0 0 / 0.06)',
                'sidebar': '4px 0 24px -4px rgb(0 0 0 / 0.15)',
                'glow': '0 0 20px -4px rgb(0 162 233 / 0.3)',
                'glow-brand': '0 0 20px -4px rgb(38 67 141 / 0.3)',
                'inner-glow': 'inset 0 1px 2px 0 rgb(255 255 255 / 0.1)',
                'soft': '0 2px 15px -3px rgb(0 0 0 / 0.07), 0 10px 20px -2px rgb(0 0 0 / 0.04)',
                'ring': '0 0 0 2px hsl(var(--ring))',
            },

            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
                'fade-in': {
                    from: { opacity: '0' },
                    to: { opacity: '1' },
                },
                'fade-in-up': {
                    from: { opacity: '0', transform: 'translateY(24px)' },
                    to: { opacity: '1', transform: 'translateY(0)' },
                },
                'slide-up': {
                    from: { opacity: '0', transform: 'translateY(16px)' },
                    to: { opacity: '1', transform: 'translateY(0)' },
                },
                'slide-in-right': {
                    from: { opacity: '0', transform: 'translateX(-16px)' },
                    to: { opacity: '1', transform: 'translateX(0)' },
                },
                'scale-in': {
                    from: { opacity: '0', transform: 'scale(0.95)' },
                    to: { opacity: '1', transform: 'scale(1)' },
                },
                'pulse-soft': {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.7' },
                },
                'shimmer': {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                'float': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
            },

            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'fade-in': 'fadeIn 0.4s ease-out',
                'fade-in-up': 'fadeInUp 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
                'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
                'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
                'scale-in': 'scaleIn 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
                'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
                'shimmer': 'shimmer 2s linear infinite',
                'float': 'float 6s ease-in-out infinite',
            },

            spacing: {
                '18': '4.5rem',
                '88': '22rem',
            },
        },
    },

    plugins: [forms],

    safelist: [
        'bg-navy',
        'bg-navy-light',
        'bg-navy-deep',
        'text-navy',
        'text-navy-light',
        'text-navy-deep',
        'bg-gold-400',
        'bg-gold-400/10',
        'bg-gold-400/15',
        'bg-gold-400/20',
        'bg-gold-500',
        'text-gold-400',
        'text-gold-500',
        'text-gold-600',
        'border-gold-400/20',
        'bg-accent-50',
        'bg-accent-100',
        'bg-accent-400',
        'bg-accent-400/10',
        'bg-accent-400/15',
        'bg-accent-400/20',
        'bg-accent-500',
        'text-accent-400',
        'text-accent-500',
        'text-accent-600',
        'border-accent-400/20',
        'bg-success-50',
        'bg-success-500',
        'bg-success-50/50',
        'text-success-500',
        'ring-success-500/10',
        'bg-danger-500',
        'text-danger-500',
        'package-bg-purple',
        'package-bg-green',
        'package-bg-red',
        'package-bg-yellow',
        'package-bg-orange',
        'package-bg-blue',
        'package-bg-pink',
        'package-bg-teal',
        'package-bg-indigo',
        'package-bg-rose',
        'package-bg-cyan',
        'package-bg-amber',
        'package-bg-emerald',
        'package-bg-violet',
        'animate-fade-in',
        'animate-fade-in-up',
        'animate-slide-up',
        'animate-scale-in',
        'animate-pulse-soft',
        'animate-shimmer',
        'animate-float',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-7',
        'grid-cols-8',
        'grid-cols-9',
        'grid-cols-10',
        'grid-cols-11',
        'grid-cols-12',
        'flex-col',
        'flex-row',
        'flex-wrap',
        'flex-nowrap',
        'items-center',
        'items-start',
        'items-end',
        'justify-center',
        'justify-between',
        'justify-start',
        'justify-end',
        'hidden',
        'block',
        'inline-block',
        'inline-flex',
        'relative',
        'absolute',
        'fixed',
        'sticky',
        'overflow-hidden',
        'overflow-y-auto',
        'overflow-x-auto',
    ]
};
